### ISSUE TITLE
Pages leak names of organisations using E-consensus

### ISSUE THREAD

**Issue by timgdavies** [aptivate/econsensus#224]
Whilst discussions are only made available to logged-in authorised users, manipulating the URL for an item reveals the name of the organisation that item belongs to, even if not logged in / authorised as a member of the organisation.

E.g.:

* https://econsensus.org/item/detail/1/
* https://econsensus.org/item/detail/11/
* https://econsensus.org/item/detail/691/

**Comment by foobacca** [comment]
Interesting, thanks for raising it. We'll look at this when we're next doing some work on the code.

**Comment by daniell** [comment]
This issue should be fixed now.
